/**
 * @generated
 * @file Button (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://happcoach.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import Link from "./webflow_modules/Basic/components/Link";

/**
 * Props for {@link Button}
 */
export type ButtonProps = {
  buttonLink?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  buttonText?: React.ReactNode;
  variant?: "Base" | "Yellow Small" | "Black" | "White";
};

/**
 * Button
 *
 * @see {@link https://happcoach.design.webflow.com | Source site in Webflow}
 */
export function Button({
  buttonLink = {
    href: "#",
  },

  buttonText = "E-Learning Solutions",
  variant = "Base",
}: ButtonProps) {
  const _styleVariantMap = {
    Base: "",
    "Yellow Small": "w-variant-9a860949-b0f2-93d5-4615-d36824d6e6c0",
    Black: "w-variant-780dfba3-0f25-6a24-b922-c3af19f03b21",
    White: "w-variant-d69c621c-cb5a-8127-8ad1-aa6609b6173b",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Link
        block={"inline"}
        button={false}
        className={`button-wrapper ${_activeStyleVariant}`}
        options={buttonLink}
      >
        <Block className={`button-block ${_activeStyleVariant}`} tag={"div"}>
          {buttonText}
        </Block>
      </Link>
    </div>
  );
}
