/**
 * @generated
 * @file NavbarDropdownCard (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://happcoach.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import Heading from "./webflow_modules/Basic/components/Heading";
import Image from "./webflow_modules/Basic/components/Image";
import Link from "./webflow_modules/Basic/components/Link";
import Paragraph from "./webflow_modules/Basic/components/Paragraph";

/**
 * Props for {@link NavbarDropdownCard}
 */
export type NavbarDropdownCardProps = {
  image?: string;
  summary?: React.ReactNode;
  title?: React.ReactNode;
};

/**
 * NavbarDropdownCard
 *
 * @see {@link https://happcoach.design.webflow.com | Source site in Webflow}
 */
export function NavbarDropdownCard({
  image = "https://cdn.prod.website-files.com/68d367f89a1176cba2647b5f/68d4d8fe3db939a628cdcdb6_Placeholder%20Image.avif",
  summary = "Unlock creative solutions through innovative design thinking techniques.",
  title = "Design Thinking Innovation",
}: NavbarDropdownCardProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Link
        block={"inline"}
        button={false}
        className={"nav-dropdown-card"}
        options={{
          href: "https://www.google.com/",
          target: "_blank",
        }}
      >
        <Image
          alt={""}
          className={"nav-dropdown-card-image"}
          height={"auto"}
          loading={"lazy"}
          src={image}
          width={"auto"}
        />
        <Block className={"nav-card-body"} tag={"div"}>
          <Heading className={"nav-card-heading"} tag={"h3"}>
            {title}
          </Heading>
          <Paragraph className={"text-size-small is-nav-card-text"}>
            {summary}
          </Paragraph>
        </Block>
      </Link>
    </div>
  );
}
